# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('time', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('organization', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
