# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160402_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='foodevent',
            name='foodtype',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
