# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160402_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
