# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_foodevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodevent',
            name='locationWithPlus',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
