# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_foodevent_locationwithplus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodevent',
            name='locationWithPlus',
        ),
    ]
