# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_foodevent_locationwithplus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodevent',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
